language: generic
services:
 - docker

# BE CAREFUL: There is a risk of outputting real credentials to logs here!
before_install:
 - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin
 - docker build -t platformoftrust/website:$TRAVIS_BUILD_NUMBER .

script:
 - docker push platformoftrust/website:$TRAVIS_BUILD_NUMBER
