language: generic
services:
 - docker

# BE CAREFUL: There is a risk of outputting real credentials to logs here!
script:
 - ./travis-validation.sh
 - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin
 - docker build -t platformoftrust/website:$TRAVIS_BUILD_NUMBER .
 - docker push platformoftrust/website:$TRAVIS_BUILD_NUMBER
